peephole prune redundant live vars, and eliminate defs to unused literals
StanzaOrg/lbstanza-old pull request #111
Opened 2021-09-14 02:09 UTC by jackbackrack

Improve dead code elimination so that ELIR is more efficient and readable.

2021-09-17 19:27 UTC, CuppoJava requested changes
Request for clarification.

2021-09-17 19:27 UTC, CuppoJava commented on compiler/stz-el.stanza
> +  ;Pending live vars to be emitted next.
Hi Jonathan, can you explain what this code is doing, and whether it is appropriate to be considered as part of dead-code elimination, or whether it should be moved to a different pass?

2021-09-17 19:27 UTC, CuppoJava commented on compiler/stz-el.stanza
> +  if optimize? :
Remove debugging code.

2021-09-17 19:27 UTC, CuppoJava commented on compiler/stz-el.stanza
> +    ;ELive as a proper usage so that object live ranges are preserved,
Change the condition: We consider ELive as a proper usage only for EDef x = v instructions, where v is an EVar.

2021-09-17 20:22 UTC, jackbackrack commented on compiler/stz-el.stanza
> +  ;Pending live vars to be emitted next.
Currently, you're checking to see if EDef varlocs are used either as args or in ELive instructions.  This change now says that EDefs with literal y's are removed if varlocs are only used in live instructions (as opposed to args).  Without this you end of with a bunch of useless literal defs.  We talked about this and you agreed.  I changed the function name to make it clearer.

2021-09-17 20:22 UTC, jackbackrack commented on compiler/stz-el.stanza
> +  if optimize? :
done.

2021-09-17 22:18 UTC, CuppoJava commented on compiler/stz-el.stanza
> +  ;Pending live vars to be emitted next.
Sorry, I meant the peephole stuff. What is that for?

2021-09-18 00:07 UTC, jackbackrack commented on compiler/stz-el.stanza
> +  ;Pending live vars to be emitted next.
The peephole stuff is for removing extra live statements and consolidating them into a single live statement.  For instance, I would see many successive ELive statements with redundant variables in them.  This collapses them into a single ELive statement with the union of those variables.  It just cleans up the ELive statements so they don't dominate the EL-IR.

2021-09-20 17:30 UTC, CuppoJava commented on compiler/stz-el.stanza
> +  ;Pending live vars to be emitted next.
Okay sounds good. Can you look into refactoring/cleaning up the logic for this pass so the logic is easier to understand?

2021-09-20 17:55 UTC, jackbackrack commented on compiler/stz-el.stanza
> +  ;Pending live vars to be emitted next.
i worked pretty hard to make the live var pruner code simple.  i'm not sure how much refactoring is possible in 12 lines of code.  perhaps i can add comments to make it simpler.  i could split it out into a separate sweep through the instructions but then it would be slower...

2021-09-20 18:39 UTC, jackbackrack commented on compiler/stz-el.stanza
> +  ;Pending live vars to be emitted next.
ok, i've pushed a new version that splits out consolidate live vars.

2021-09-26 17:16 UTC, merged