Refactored indexing algorithm and DefinitionsDatabase
StanzaOrg/lbstanza-old pull request #150
Opened 2022-03-30 16:15 UTC by m-hilgendorf

- Added support for visibility modifiers in the definitions database
- Altered algorithm to flatten IL-IR into definitions and their visibility
- Split indexing functions into helpers to make it easier to test
- Added unit tests to check each step of the indexing process.

2022-03-30 22:33 UTC, CuppoJava requested changes
Fantastic work. Implement is both more powerful and cleaner than before.

2022-03-30 22:33 UTC, CuppoJava commented on compiler/stz-defs-db-serializer.stanza
> +public defstruct PackageImportPrefix :
[P] Thanks this is necessary, but it seems to be unused currently.
What is supposed to create this structure? I also recommend changing
the names and types to more closely match their original names in
`il-ir.stanza`. See the `IPrefix` struct in `il-ir.stanza`.

So:
```
  sources => names
  Tuple<Symbol> => False|Tuple<Symbol>
  prefix:Symbol => prefix:String
```

The `False` case for `names` is used when the user types:

  prefix => pre-

Which indicates to use a single prefix for absolutely everything. See
the `IPrefix` type in `il-ir.stanza`.

After you change `Tuple<Symbol>` to `False|Tuple<Symbol>`, you'll have
to copy over `read-opt` and `write-opt` from `stz-pkg.stanza` for the
serialization. See the usages of `opt<FileInfo>(...)` for examples on
how they are used.

public defstruct IPrefix :
  names: False|Tuple<Symbol>
  prefix: String
with:
  printer => true

2022-03-30 22:33 UTC, CuppoJava commented on compiler/stz-defs-db.stanza
>    platform: Symbol|False
Don't allow this platform to be false. Fill it with OUTPUT-PLATFORM when this is created.

2022-03-30 22:33 UTC, CuppoJava commented on compiler/stz-defs-db.stanza
> +  val db-platform =
Move this logic out of here. See the comment beside `platform:Symbol|False`.

2022-03-30 22:33 UTC, CuppoJava commented on compiler/stz-defs-db.stanza
> +  var print? = false
Debug code.

2022-03-30 22:33 UTC, CuppoJava commented on compiler/stz-defs-db.stanza
> +        ; Case 1: We encounter a visibility node. Walk its
I like the structure of the comments here. It makes both the intention and implementation of the algorithm very clear.

2022-03-30 22:33 UTC, CuppoJava commented on compiler/stz-defs-db.stanza
> +  generate :
`generate<Indexed>` for clarity.

2022-03-31 15:14 UTC, m-hilgendorf commented on compiler/stz-defs-db.stanza
>    platform: Symbol|False
This comes directly from the CLI command, so I added it to `stz-main.stanza`. It turns out that the previous implementation always gave `false` for `platform` and it's not immediately useful to support cross-compilation for indexing commands, so I hardcoded it to OUTPUT-PLATFORM.

2022-03-31 15:14 UTC, m-hilgendorf commented on compiler/stz-defs-db.stanza
> +  var print? = false
Removed! Thank you

2022-03-31 15:14 UTC, m-hilgendorf commented on compiler/stz-defs-db.stanza
> +  generate :
Fixed!

2022-03-31 15:14 UTC, m-hilgendorf commented on compiler/stz-defs-db-serializer.stanza
> +public defstruct PackageImportPrefix :
I split out the construction of `PackageDefinition` objects into a helper called `index-definitions` that now appropriately handles the extraction of imports and prefixes. 

Thank you for the pointer on `read-opt` and `write-opt`!

2022-03-31 15:14 UTC, m-hilgendorf commented on compiler/stz-defs-db.stanza
> +  val db-platform =
Removed!

2022-04-02 06:42 UTC, merged