type raw array and add precise inference rule for objectget and newob…
StanzaOrg/lbstanza-old pull request #63
Opened 2020-02-22 16:04 UTC by jackbackrack

Typed raw array so that in optimized mode the element types are propagated properly.  Added a couple type inference rules so that the element types and object types are precisely inferred.

2020-02-24 23:18 UTC, CuppoJava commented
Merged, the RawArray parametric types, but still need to review the changes to the type inference.

2020-02-24 23:19 UTC, CuppoJava commented on compiler/stz-el.stanza
> -      (i:ENewObject) : trusted(x(i))
What was the reasoning for moving this out of this section and into the next?

2020-02-24 23:19 UTC, CuppoJava commented on compiler/stz-el.stanza
> +      (i:EObjectGet) : trusted(x(i))
Looks good.

2020-02-25 00:36 UTC, jackbackrack commented on compiler/stz-el.stanza
> -      (i:ENewObject) : trusted(x(i))
i tested and found in fact it doesn't affect the results to leave it the way it was.  the important thing is to have rawarray be typed it appears.

2020-02-25 16:23 UTC, CuppoJava requested changes

2020-02-25 16:23 UTC, CuppoJava commented on compiler/stz-el.stanza
> +  spit("out.txt", cur-package)
Can you get rid of the debug output?

2020-02-25 16:53 UTC, jackbackrack commented
done.

2020-02-25 18:30 UTC, merged