Introduce `stz_*` types in Stanza runtime
StanzaOrg/lbstanza-old pull request #91
Opened 2021-08-31 19:00 UTC by tylanphear

In the Stanza runtime, we have a bunch of C code that is called from Stanza. In doing so, it is important that we make sure that the size/signedness of types in Stanza is preserved when passed over the boundary to C. This is especially necessary because, while types in Stanza may often have the same name as types in C, their representation can be very different.

One place where our usage of C types caused issue was `void* stz_malloc(long)`, which has the corresponding Stanza definition `extern stz_malloc: long -> ptr<?>`. In Stanza, `long` is always an signed 64 bit integer, whereas in C `long` can be any integer at least 32 bits wide. Indeed, in C on Windows `long` is a 32-bit signed integer and on Linux `long` is a 64-bit signed integer.

In order to control the representation of types passed along the boundary, this patch introduces `stz_*` types (e.g. `stz_long`) whose representation matches exactly that of the corresponding type in Stanza. These types should be used at the boundary between C and Stanza in order to prevent size/signedness issues. For example, the above `stz_malloc` becomes `void* stz_malloc(stz_long)`. Additionally included are also a set of macros for conversion between Stanza strings (`stz_byte*`) and C-strings (`char*`).

2021-08-31 19:19 UTC, OlegPliss commented
There are other places where lostanza`long` is used instead of C `size_t`, i.e. `memset` in core.stanza.

2021-08-31 20:33 UTC, tylanphear commented
> There are other places where lostanza`long` is used instead of C `size_t`, i.e. `memset` in core.stanza.

Yes, this is true. At least, since we only compile on 64-bit, we know that `sizeof(long) == sizeof(size_t)`, but there is still a signedness mismatch there, since `long` is signed and `size_t` is unsigned.

I think the correct solution to this is to create types in the Stanza `clib` that correspond to C types. I know that this is the approach used in the `libc` crate in Rust and the `ctypes` module in Python. The implementation of this is trivial to state, but could be more involved, as I don't know of any ways to control representation in Stanza (outside of the existing builtin types).

2021-08-31 21:12 UTC, OlegPliss commented
Usually the solution for native function interface is two-fold: introduce native types to the language (i.e. `size_t` in stanza clb) and language types to native code (i.e. `stz_long` in `stanza-types.h` included to `runtime/driver.c`).

2021-08-31 21:15 UTC, tylanphear commented
I agree 100%. With this PR we will have the latter half of the solution. We will almost certainly need the former in the future.

2021-08-31 22:12 UTC, CuppoJava requested changes
Thank you! Small question about `fread` et al.

2021-08-31 22:12 UTC, CuppoJava commented on runtime/driver.c
> +  return (stz_int)fread(data, 1, len, f);
Should this be `stz_long` since the return type is `stz_long`?

2021-08-31 22:12 UTC, CuppoJava commented on runtime/driver.c
> +  return (stz_int)fwrite(data, 1, len, f);
Should this be stz_long since the return type is stz_long?

2021-08-31 22:12 UTC, CuppoJava commented on runtime/driver.c
> +  stz_long pc;
Thank you for catching that.

2021-08-31 22:25 UTC, tylanphear commented on runtime/driver.c
> +  return (stz_int)fread(data, 1, len, f);
Yes, absolutely. Not sure what happened here.

2021-08-31 22:26 UTC, tylanphear commented on runtime/driver.c
> +  return (stz_int)fwrite(data, 1, len, f);
Ditto to above

2021-09-01 00:09 UTC, tylanphear commented
> Thank you! Small question about `fread` et al.

Should be fixed now! Let me know if you have further comments/concerns.

2021-09-01 02:09 UTC, CuppoJava approved these changes
Looks good.

2021-09-01 02:09 UTC, merged